# Generated by Django 5.2.8 on 2026-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Адрес доставки'),
        ),
    ]
